# Configuracion del tema de alacritty
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

# Configuracion de Windows
[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.93

[window.padding]
x = 15
y = 20

[window.class]
instance = "Alacritty"
general = "Alacritty"

# Configuracion de la tipografia
[font]
size = 13.5

[font.bold]
family = "MesloLGS NF"
style = "Heavy"

[font.bold_italic]
family = "MesloLGS NF"
style = "Heavy Italic"

[font.italic]
family = "MesloLGS NF"
style = "Medium Italic"

[font.normal]
family = "MesloLGS NF"
style = "Medium"

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "Q", mods = "Control|Shift", action = "Quit" },
]